name: Deploy Theme

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Type "deploy" to confirm deployment'
        required: true
        default: ''

jobs:
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest

    steps:
      - name: Validate confirmation
        run: |
          if [ "${{ github.event.inputs.confirm }}" != "deploy" ]; then
            echo "Deployment cancelled. You must type 'deploy' to confirm."
            exit 1
          fi

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build assets
        run: npm run build

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: 107.180.40.145
          username: render034@mdpedi.com
          password: ${{ secrets.FTP_PASSWORD }}
          #/home/rfkvew2zjpqj/public_html#
          server-dir: /wp-content/themes/mdpedi-2025-theme/
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/.DS_Store
            **/package.json
            **/package-lock.json
            **/vite.config.js
            **/.github/**
